# Sử dụng Node.js để build React  
FROM node:18 AS build  
WORKDIR /app  
COPY package*.json ./  
RUN npm install  
COPY . .  
RUN npm run build  

# Sử dụng Nginx để serve React  
FROM nginx:alpine  
COPY --from=build /app/dist /usr/share/nginx/html  
EXPOSE 5173  
CMD ["nginx", "-g", "daemon off;"]
