version: "3.8"
services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile.backend
    ports:
      - "3000:3000"
    env_file:
      - ./Backend/.env   # Load biến môi trường từ file .env
    volumes:
      - ./Backend:/app
  
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./Frontend:/app:delegated
